### ISSUE TITLE
docstrings

### ISSUE THREAD

**Issue by MichaelHatherly** [PoisotLab/EcologicalNetwork.jl#33]
Hi @tpoisot,

I noticed the comment [here](https://github.com/PoisotLab/EcologicalNetwork.jl/blob/4de8f7d71484a7c168fcc2293285bdb2e5aa96ac/src/EcologicalNetwork.jl#L9-L13) about importing the correct ``@doc`` macro. It's solvable by switching to bare docstrings, which were merged recently into base and are supported by Docile in Julia 0.3 as well. If you'd like I can open a quick PR with the necessary changes.

**Comment by tpoisot** [comment]
That would help greatly!
