### ISSUE TITLE
How'd you get the icons in the commits?

### ISSUE THREAD

**Issue by sbromberger** [PoisotLab/EcologicalNetwork.jl#81]
Hi @tpoisot - was looking at your repo and noticed icons in commits. How'd you do that? :)

**Comment by tpoisot** [comment]
You just need to type the name of the emoji first!

`:bug:` becomes :bug: - I find this useful for visual grepping (also actual grepping!)

**Comment by sbromberger** [comment]
brilliant. Thanks :)

**Comment by sbromberger** [comment]
(I assume this is in the commit message itself?)

**Comment by tpoisot** [comment]
Yes -- first line.
